version: "3.2"

services:
  website:
    build: 'website'
    image: thefirstspine_website_image
    container_name: thefirstspine_website_container
    networks:
      default:
    volumes:
      - ${DATA}:/data/
      - /var/log:/var/log
    ports:
      - "${PORT}:${PORT}"
    tty: true
    env_file:
      - .env

networks:
  default:
    driver: bridge
