on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

name: Compass metrics hourly jobs

concurrency:
  group: 'compass-metrics-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    name: "Test command to check the action"
    runs-on: ubuntu-latest
    steps:
      - name: Run the "test" command
        uses: thefirstspine-org/github-action-compass-metrics@master
        with:
          command: 'test'
  availability:
    name: "Check availability of the service"
    runs-on: ubuntu-latest
    steps:
      - name: Run the "availability" command
        uses: thefirstspine-org/github-action-compass-metrics@master
        with:
          command: 'availability'
          atlassianUserApiKey: ${{ secrets.ATLASSIAN_API_KEY }}
          atlassianUserEmail: 'teddy@thefirstspine.fr'
          gatewayDomain: 'thefirstspine.atlassian.net'
          metricSourceId: 'ari:cloud:compass:6ea2c72c-9b15-49d9-bd9d-72a5b6d1b3e1:metric-source/f792fe52-6af8-47ca-9398-ce0c44305c1b/f86e9499-d5e0-4816-a131-13389049058b'
          serviceUrl: 'https://www.thefirstspine.fr'
